Controllers/BenefitController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BenefitUploader.Helper;
using BenefitUploader.Models;
using System.Data.SqlClient;
using System.Web;
using OfficeOpenXml;
using System.Threading;
using System.Net.Mail;
using System.Net;
using System.Globalization;

namespace BenefitUploader.Controllers
{
    public class BenefitController : Controller
    {
        private readonly DbBenefitUploaderContext _context;
        private readonly IHostingEnvironment _hostingEnvironment;

        public BenefitController(DbBenefitUploaderContext context, IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
        }

        private bool IsSession()
        {
            if (HttpContext.Session != null)
            {
                var name = HttpContext.Session.GetString("uid");

                if (!String.IsNullOrEmpty(name))
                {
                    return true;
                }
            }

            return false;
        }

        // GET: Benefits
        public async Task<IActionResult> Index()
        {
            return View(await _context.Benefits.ToListAsync());
        }

        public IActionResult Upload()
        {
            if (!IsSession())
            {
                return RedirectToAction(nameof(AuthController.SignIn), "Auth");
            }
            string webRootPath = _hostingEnvironment.WebRootPath;
            ViewData["Status"] = new List<string>();// HttpContext.Session.GetString("Status"); ;
            List<Benefit> reportList = new List<Benefit>();
            ViewData["List"] = reportList;
            return View();
        }

        [HttpPost]
        [Route("Benefit/Upload")]
        public IActionResult Upload(IFormFile reportfile)
        {
            if (!IsSession())
            {
                return RedirectToAction(nameof(AuthController.SignIn), "Auth");
            }
            string folderName = "Upload";
            string webRootPath = _hostingEnvironment.WebRootPath;
            string newPath = Path.Combine(webRootPath, folderName);
            // Delete Files from Directory
            System.IO.DirectoryInfo di = new DirectoryInfo(newPath);

            if (!Directory.Exists(newPath))// Crate New Directory if not exist as per the path
            {
                Directory.CreateDirectory(newPath);
            }
            foreach (FileInfo filesDelete in di.GetFiles())
            {
                filesDelete.Delete();
            }// End Deleting files form directories

            var fiName = "Upload" + Path.GetExtension(reportfile.FileName);
            using (var fileStream = new FileStream(Path.Combine(newPath, fiName), FileMode.Create))
            {
                reportfile.CopyTo(fileStream);
            }
            List<Benefit> reportList = new List<Benefit>();
            // Get uploaded file path with root
            string rootFolder = _hostingEnvironment.WebRootPath;
            string fileName = @"Upload\" + fiName;
            FileInfo file = new FileInfo(Path.Combine(rootFolder, fileName));
            List<string> status = new List<string>();
            using (ExcelPackage package = new ExcelPackage(file))
            {
                ExcelWorksheet workSheet = package.Workbook.Worksheets[0];
                int totalRows = workSheet.Dimension.Rows;
                for (int i = 2; i <= totalRows + 1; i++)
                {
                    try
                    {
                        string TahunPerobatan = workSheet?.Cells[i, 1]?.Value?.ToString();
                        string Nik = workSheet?.Cells[i, 2]?.Value?.ToString();
                        string Name = workSheet?.Cells[i, 3]?.Value?.ToString();
                        string PersArea = workSheet?.Cells[i, 4]?.Value?.ToString();
                        string CutOffDate = workSheet?.Cells[i, 5]?.Value?.ToString();
                        string LimitTahunan = workSheet?.Cells[i, 6]?.Value?.ToString();
                        string KlaimDibayar = workSheet?.Cells[i, 7]?.Value?.ToString();
                        string OverPlafon = workSheet?.Cells[i, 8]?.Value?.ToString();
                        string Remark = string.Empty;
                        string date = CutOffDate.Replace(".", "");
                        date = date.Replace("-", "");
                        date = date.Replace("/", "");
                        date = string.Concat(date.Substring(2, 2), "-", date.Substring(0, 2), "-", date.Substring(4, 4));

                        //if (_context.Benefits.Any(x => x.EmployeeID == Nik && x.PersArea == PersArea && x.CutOffDate.ToString("MM-dd-yyyy") == date
                        //    && x.KlaimDibayar == Convert.ToDouble(KlaimDibayar).ToString("N", CultureInfo.InvariantCulture)
                        //    && x.LimitTahunan == Convert.ToDouble(LimitTahunan).ToString("N", CultureInfo.InvariantCulture)
                        //    && x.OverPlafon == Convert.ToDouble(OverPlafon).ToString("N", CultureInfo.InvariantCulture)
                        //    ))
                        //{
                        //    // Exists
                        //    Remark = "Data exists";
                        //}

                        //var dupe = reportList
                        //      .Where(g => g.EmployeeID == Nik && g.PersArea == PersArea && g.CutOffDate.ToString("MM-dd-yyyy") == date)
                        //      .ToList();
                        //if (dupe.Count > 0)
                        //{
                        //    Remark = "Duplicate";
                        //}
                        //if (PersArea != "2000")
                        //{
                        //    Remark = "Site must be 2000";
                        //}


                        Benefit ben = new Benefit();
                        ben.EmployeeID = Nik;
                        ben.Name = Name;
                        ben.PersArea = PersArea;

                        ben.CutOffDate = Convert.ToDateTime(date);
                        ben.LimitTahunan = Convert.ToDouble(LimitTahunan).ToString("N0", CultureInfo.InvariantCulture);
                        ben.KlaimDibayar = Convert.ToDouble(KlaimDibayar).ToString("N0", CultureInfo.InvariantCulture);
                        ben.OverPlafon = Convert.ToDouble(OverPlafon).ToString("N0", CultureInfo.InvariantCulture);
                        ben.CreatedBy = HttpContext.Session.GetString("uid");
                        ben.CreatedDate = DateTime.Now;
                        ben.Description = String.IsNullOrEmpty(Remark) ? "Success" : Remark;
                        ben.TahunPerobatan = TahunPerobatan;
                        reportList.Add(ben);
                    }
                    catch (Exception Ex)
                    {
                        // Exception
                    }
                }
            }
            ViewData["List"] = reportList;

            var result2 = reportList
                          .Where(g => g.Description == "Success")
                          .ToList();
            foreach (Benefit list in result2)
            {

                SmtpClient client = new SmtpClient("webmail.bukitmakmur.com");
                client.UseDefaultCredentials = false;
                //client.Credentials = new NetworkCredential("k2adminprod", "Hjiqfbo3Nq4JQSJOKsoi");
                client.Credentials = new NetworkCredential("hrservicecenter", "Bumabisa20@)");

                MailMessage mailMessage = new MailMessage();
                mailMessage.From = new MailAddress("hrservicecenter@bukitmakmur.com");
                //mailMessage.From = new MailAddress("k2adminprod@bukitmakmur.com");
                mailMessage.IsBodyHtml = true;
                Employee employ = _context.Employees.Where(j => j.EmployeeID == list.EmployeeID).FirstOrDefault();
                if (employ != null)
                {
                    list.Name = employ.Name.Replace(".","");
                    //list.Description = "";
                    _context.Benefits.Add(list);
                    _context.SaveChanges();
                    //mailMessage.To.Add("cahya.imantiara@bukitmakmur.com");
                    //mailMessage.To.Add("liani.susanto@bukitmakmur.com");
                    //mailMessage.To.Add("dewi.susanti@bukitmakmur.com");
                    mailMessage.CC.Add("anik.yuli@bukitmakmur.com");
                    mailMessage.CC.Add("dimas.triantoro@bukitmakmur.com");
                    //mailMessage.Bcc.Add("cahya.imantiara@bukitmakmur.com");
                    mailMessage.To.Add(employ.Email);
                    string gender = employ.Gender == "1" ? "Bapak " : "Ibu ";
                    string body = "<font face='calibri' size ='3'>";
                    body += " Dear " + gender + employ.Name + ",<br/> <br/>";
                    body += " Sesuai dengan laporan klaim rawat jalan per " + list.CutOffDate.ToString("dd MMMM yyyy") + " yang diterima dari Asuransi, maka kami sampaikan estimasi sisa plafon Rawat Jalan sebagai berikut:<br/><br/>"
                    + "<table  border='1' border-collapse='collapse' width=' 100%' font-face ='calibri' font-size='3' align='center'><tr align='center'><td>Tahun Perobatan</td><td>NIK</td><td>Nama Karyawan</td><td>Plafon Rawat Jalan</td><td>Estimasi Penggunaan Plafon</td><td>Estimasi Sisa Plafon</td></tr> "
                    + "<tr align='center'><td> " + list.TahunPerobatan + "</td><td> " + list.EmployeeID + "</td><td>" + employ.Name + "</td><td>" + list.LimitTahunan + "</td><td>" + list.KlaimDibayar + "</td><td>" + list.OverPlafon + "</td></tr> </table><br/>"

                    + @"<b>Note :</b><br/>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Upload Notif Email Sisa Plafon HR </title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body style="background-color:aliceblue">
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-right">

                <img src="~/images/logo.png" width="175" height="53" class="logo" />
            </div>
            <div class="navbar-collapse collapse right">

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand" style="color:white">Upload Email Notification HR</a>
                <ul class="nav navbar-nav">
                    <li>
                        <a href="@Url.Action("Index", "Benefit")" class="nav-link">
                            <span class="pcoded-micon"><i class="icon-list"></i></span><span class="pcoded-mtext">Uploaded Benefit List</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Upload", "Benefit")" class="nav-link">
                            <span class="pcoded-micon"><i class="icon-upload"></i></span><span class="pcoded-mtext">Upload Plafon Benefit</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Index", "LoanMedicals")" class="nav-link">
                            <span class="pcoded-micon"><i class="icon-list"></i></span><span class="pcoded-mtext">Uploaded Loan Medical List</span>
                        </a>
                    </li>
                    <li>
                        <a href="@Url.Action("Upload", "LoanMedicals")" class="nav-link">
                            <span class="pcoded-micon"><i class="icon-upload"></i></span><span class="pcoded-mtext">Upload Loan Medical</span>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="navbar-collapse collapse">
               
            </div>
        </div>
    </div>

    <div class="container body-content" style="background-color:white">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - BUMA</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_LayoutAccess.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title - BUMA Authenticator</title>

    <environment include="Development">
        <!-- Favicon icon -->
        <link rel="icon" href="~/themes/images/favicon.ico" type="image/x-icon">
        <!-- vendor css -->
        <link rel="stylesheet" href="~/themes/css/style.css" />
        <!-- fontawesome icon -->
        <link rel="stylesheet" href="~/themes/fonts/fontawesome/css/fontawesome-all.min.css" />
        <!-- animation css -->
        <link rel="stylesheet" href="~/themes/plugins/animation/css/animate.min.css" />
    </environment>

    <environment exclude="Development">
        <!-- Favicon icon -->
        <link rel="icon" href="~/themes/images/favicon.ico" type="image/x-icon">
        <link rel="stylesheet" href="~/themes/css/style.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/themes/fonts/fontawesome/css/fontawesome-all.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="~/themes/plugins/animation/css/animate.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div>
        @RenderBody()
    </div>

    <environment include="Development">
        <!-- Required Js -->
        <script src="~/themes/js/vendor-all.min.js"></script>
        <script src="~/themes/plugins/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/themes/js/pcoded.min.js"></script>
    </environment>
    <environment exclude="Development">
        <!-- Required Js -->
        <script src="~/themes/js/vendor-all.min.js"></script>
        <script src="~/themes/plugins/bootstrap/js/bootstrap.min.js"></script>
        <script src="~/themes/js/pcoded.min.js"></script>
    </environment>
</body>
</html>